version: "3.6"

services:
  gateway:
    image: gateway
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always

  votingapp:
    image: votingapp
    build:
      context: ./src/votingapp
      dockerfile: Dockerfile
  
  votingapp-test:
    image: votingapp-test
    build:
      context: ./test
      dockerfile: Dockerfile
    environment:
      VOTING_URL: http://votingapp:8080/vote
