version: "3.6"

services:
  gateway:
    image: ${REGISTRY-joancliment}/my-gateway:${TAG-latest}
    build:
      context: ./src/gateway
    ports:
      - 8080:8080
    restart: always

  votingapp:
    image: ${REGISTRY:-joancliment}/votingapp
    build:
      context: ./src/votingapp
      dockerfile: Dockerfile

  votingapp-test:
    image: votingapp-test
    build:
      context: ./test
    environment: 
      VOTING_URL: http://votingapp/vote
